### PR TITLE
Replace applet declaration macros with template

### PR DESCRIPTION
**Pull request by qiemem**
Note: This is untested on hardware. Just tried isolating the code from #89

### CODE REVIEW

**Comment by djphazer** [comment]
Confirmed this works and runs, but both code size and RAM usage goes up a bit... and I still don't fully understand why. Standard library code getting included? or differences in the data structure?

**Comment by qiemem** [comment]
Hmm, so here's what I'm seeing:

dev/1.8
```
teensy_size: Memory Usage on Teensy 4.1:
teensy_size:   FLASH: code:300748, data:105996, headers:8996   free for files:7710724
teensy_size:    RAM1: variables:188576, code:292336, padding:2576   free for local variables:40800
teensy_size:    RAM2: variables:52320  free for malloc/new:471968
```

template-applets
```
teensy_size: Memory Usage on Teensy 4.1:
teensy_size:   FLASH: code:303916, data:104972, headers:8900   free for files:7708676
teensy_size:    RAM1: variables:189760, code:295504, padding:32176   free for local variables:6848
teensy_size:    RAM2: variables:52320  free for malloc/new:471968
```

Looks like the relatively small increase in RAM1 code size leaked into another 32kb block, causing a big increase in padding. I'll see what I can do. Because I originally did this with the audio applets stuff, I wasn't paying too close of attention to memory.

**Comment by qiemem** [comment]
Alright, think I finally got it. The code/memory increase was mainly due to just the amount of template specialization information that had to be preserved after compilation. This new approach only uses the template info during compilation by processing it in a `constexpr` constructor and storing the instance tuples as `inline static`. It also is a much smaller change than before because the result is an `Applet`s array, just like in the original code, so `APP_HEMISPHERE` and `APP_QUADRANTS` don't need to change. 

Memory info for 4.1. Ends up using 32 bytes more variables, but 592 bytes less code in RAM1!

```
teensy_size: Memory Usage on Teensy 4.1:
teensy_size:   FLASH: code:300156, data:105996, headers:8564   free for files:7711748
teensy_size:    RAM1: variables:188608, code:291744, padding:3168   free for local variables:40768
teensy_size:    RAM2: variables:52320  free for malloc/new:471968
```

Memory info for 3.2 (via pewpewpew):

Templates:
```
RAM:   [========  ]  81.9% (used 53696 bytes from 65536 bytes)
Flash: [==========]  97.8% (used 256384 bytes from 262144 bytes)
```

Macros:
```
RAM:   [========  ]  80.1% (used 52512 bytes from 65536 bytes)
Flash: [==========]  98.1% (used 257200 bytes from 262144 bytes)
```

Oh, and again, I haven't tested this on real hardware, but I'll be back home in a few days, so can test it then if you don't get to it first.

**Comment by qiemem** [comment]
Oh, this was super critical in figuring out how to do it without increasing memory: https://godbolt.org/z/W83f9aqPP.
Note that the base class in the example code *has* to have a virtual method to be an accurate test. But to see the kind of thing that was taking up so much code before, remove `inline static` from the `pool` field and watch the compiled code just explode in size as it preserves all the specializations of `std::get` and such.

**Comment by djphazer** [comment]
Brilliant! These are the kind of C++ lessons I'm interested in - compile-time template usage/syntax, memory optimizations, etc. I don't think I would have figured out some of that variadic template syntax on my own! Thank you!

Definitely going to digest this and acquaint myself with it in godbolt...
Also, quite pleased that the better solution ended up being a less intrusive code change ;)

**Comment by djphazer** [comment]
I just force-pushed `dev/1.8` after rebasing, this PR included: https://github.com/djphazer/O_C-Phazerville/commit/5a544dd0bac7b8b530d089e1e9048107b01c7081

It might be better to target the `phazerville` branch going forward, but it's nbd

**Pull request closed without merging**
